# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '小组', 'verbose_name_plural': '小组'},
        ),
        migrations.AlterModelOptions(
            name='newmember',
            options={'verbose_name': '报名者', 'verbose_name_plural': '报名者'},
        ),
        migrations.AlterField(
            model_name='newmember',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
